# SPDX-FileCopyrightText: 2026 Lord-Valen
#
# SPDX-License-Identifier: CC0-1.0

name: Deploy docs to Pages

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: nix build .#packages.x86_64-linux.docs-mdbook
      - name: Stage output
        run: |
          cp -r --no-preserve=mode result/ dist/
          echo "nix-result-checks.laughing-man.xyz" > dist/CNAME
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v4
        with:
          path: dist/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
